[2016-12-14 19:24:34,481: INFO/MainProcess] beat: Starting...
/usr/local/lib/python2.7/site-packages/celery/platforms.py:766: RuntimeWarning: You are running the worker with superuser privileges, which is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,

[2016-12-14 19:24:34,532: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:24:34,596: INFO/MainProcess] Connected to redis://redis:6379/0
[2016-12-14 19:24:34,602: INFO/MainProcess] mingle: searching for neighbors
[2016-12-14 19:24:35,607: INFO/MainProcess] mingle: all alone
/usr/local/lib/python2.7/site-packages/celery/fixups/django.py:254: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2016-12-14 19:24:35,617: WARNING/MainProcess] /usr/local/lib/python2.7/site-packages/celery/fixups/django.py:254: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2016-12-14 19:24:35,618: WARNING/MainProcess] celery@4573c5801e22 ready.
[2016-12-14 19:24:35,834: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[9b0a8e41-52c1-4eaf-880b-497698a88a46]
[2016-12-14 19:24:35,839: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[9b0a8e41-52c1-4eaf-880b-497698a88a46] succeeded in 0.00294605901581s: True
[2016-12-14 19:25:34,559: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:25:34,562: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[0172d44a-25f4-40b7-9def-7f04e36facdf]
[2016-12-14 19:25:34,564: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[0172d44a-25f4-40b7-9def-7f04e36facdf] succeeded in 0.00128429598408s: True
[2016-12-14 19:26:34,606: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:26:34,608: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[ed832641-d27c-4fa9-bb0d-c881a8669276]
[2016-12-14 19:26:34,611: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[ed832641-d27c-4fa9-bb0d-c881a8669276] succeeded in 0.00176033499883s: True
[2016-12-14 19:27:34,652: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:27:34,655: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[59f18e6c-aeea-40fd-93a9-132782e8c26d]
[2016-12-14 19:27:34,658: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[59f18e6c-aeea-40fd-93a9-132782e8c26d] succeeded in 0.00204866300919s: True
[2016-12-14 19:28:34,684: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:28:34,686: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[691af790-1372-4ad9-9599-60c34d4f9623]
[2016-12-14 19:28:34,688: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[691af790-1372-4ad9-9599-60c34d4f9623] succeeded in 0.00119423499564s: True
[2016-12-14 19:29:34,732: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:29:34,735: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[f6df2c4d-7a96-484d-b9e4-9a5fe744b7b2]
[2016-12-14 19:29:34,737: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[f6df2c4d-7a96-484d-b9e4-9a5fe744b7b2] succeeded in 0.00162498001009s: True
/usr/local/lib/python2.7/site-packages/celery/platforms.py:766: RuntimeWarning: You are running the worker with superuser privileges, which is
absolutely not recommended!

Please specify a different user using the -u option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,

[2016-12-14 19:36:30,799: INFO/MainProcess] beat: Starting...
[2016-12-14 19:36:30,943: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:36:30,971: INFO/MainProcess] Connected to redis://redis:6379/0
[2016-12-14 19:36:30,984: INFO/MainProcess] mingle: searching for neighbors
[2016-12-14 19:36:32,005: INFO/MainProcess] mingle: all alone
/usr/local/lib/python2.7/site-packages/celery/fixups/django.py:254: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2016-12-14 19:36:32,029: WARNING/MainProcess] /usr/local/lib/python2.7/site-packages/celery/fixups/django.py:254: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2016-12-14 19:36:32,031: WARNING/MainProcess] celery@e4db44bc034a ready.
[2016-12-14 19:36:32,251: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[2997e72a-b370-45e5-a6b6-09b132dc2945]
[2016-12-14 19:36:32,254: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[2997e72a-b370-45e5-a6b6-09b132dc2945] succeeded in 0.00262795199524s: True
[2016-12-14 19:37:31,002: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:37:31,006: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[a515fe7e-932a-4e1e-b247-acaa0bdaffa1]
[2016-12-14 19:37:31,009: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[a515fe7e-932a-4e1e-b247-acaa0bdaffa1] succeeded in 0.00264218900702s: True
[2016-12-14 19:38:31,043: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:38:31,045: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[409dda35-6be8-4c72-81f8-330f87b7fccb]
[2016-12-14 19:38:31,047: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[409dda35-6be8-4c72-81f8-330f87b7fccb] succeeded in 0.00123156301561s: True
[2016-12-14 19:39:31,084: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:39:31,086: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[c8a78169-b4e7-46ff-8adf-c9277be87e9d]
[2016-12-14 19:39:31,088: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[c8a78169-b4e7-46ff-8adf-c9277be87e9d] succeeded in 0.0012816269882s: True
[2016-12-14 19:40:31,136: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:40:31,139: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[82d480c2-59d5-40f8-b4e7-a0a6cbae305b]
[2016-12-14 19:40:31,141: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[82d480c2-59d5-40f8-b4e7-a0a6cbae305b] succeeded in 0.00158909900347s: True
[2016-12-14 19:41:31,188: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:41:31,191: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[10a6fae2-c811-474f-b762-d53aa28bd435]
[2016-12-14 19:41:31,195: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[10a6fae2-c811-474f-b762-d53aa28bd435] succeeded in 0.00209821300814s: True
[2016-12-14 19:42:31,197: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:42:31,201: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[024246e3-5abc-44f5-8f18-0b0fc6617665]
[2016-12-14 19:42:31,204: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[024246e3-5abc-44f5-8f18-0b0fc6617665] succeeded in 0.00189386398415s: True
[2016-12-14 19:43:31,245: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:43:31,248: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[9ce470c8-055e-427c-8faf-7e37ad37a548]
[2016-12-14 19:43:31,250: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[9ce470c8-055e-427c-8faf-7e37ad37a548] succeeded in 0.00150077597937s: True
[2016-12-14 19:44:31,298: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:44:31,301: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[86adad09-df3c-455e-881f-4ed8d42cc689]
[2016-12-14 19:44:31,303: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[86adad09-df3c-455e-881f-4ed8d42cc689] succeeded in 0.00171714901808s: True
[2016-12-14 19:45:31,300: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:45:31,304: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[732ccbfb-63de-42e8-bf69-24fd2a056500]
[2016-12-14 19:45:31,306: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[732ccbfb-63de-42e8-bf69-24fd2a056500] succeeded in 0.00141314099892s: True
[2016-12-14 19:46:31,356: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:46:31,358: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[94eb2365-7a35-44fe-9b04-fa0240cf9359]
[2016-12-14 19:46:31,361: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[94eb2365-7a35-44fe-9b04-fa0240cf9359] succeeded in 0.00166592502501s: True
[2016-12-14 19:47:31,382: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:47:31,384: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[39442d01-0ba6-4318-8b92-902f8866f537]
[2016-12-14 19:47:31,387: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[39442d01-0ba6-4318-8b92-902f8866f537] succeeded in 0.00157674201182s: True
[2016-12-14 19:48:31,415: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:48:31,418: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[c73b0e2f-aee5-4726-a6ff-45eb821b659a]
[2016-12-14 19:48:31,421: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[c73b0e2f-aee5-4726-a6ff-45eb821b659a] succeeded in 0.00142968099681s: True
[2016-12-14 19:49:31,467: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:49:31,470: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[e9c346a4-6079-497a-aaf7-41f5ecbf2205]
[2016-12-14 19:49:31,483: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[e9c346a4-6079-497a-aaf7-41f5ecbf2205] succeeded in 0.0114889840188s: True
[2016-12-14 19:50:31,521: INFO/MainProcess] Scheduler: Sending due task write_a_new_file (docker_django.apps.cyder.periodic_tasks.test)
[2016-12-14 19:50:31,525: INFO/MainProcess] Received task: docker_django.apps.cyder.periodic_tasks.test[e9dbc65f-9589-4de7-bf31-5da6fd9c222d]
[2016-12-14 19:50:31,534: INFO/MainProcess] Task docker_django.apps.cyder.periodic_tasks.test[e9dbc65f-9589-4de7-bf31-5da6fd9c222d] succeeded in 0.00780936802039s: True
